name: ride_revo
description: Ride Revo provides an app-based bike service that connects people to rides. It is only for females.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  cloud_firestore: ^4.8.0
  firebase_database: ^10.2.2
  image_picker: ^0.8.7+5
  uuid: ^3.0.7
  google_sign_in: ^6.1.3
  unicons: ^2.1.1
  google_maps_flutter: ^2.2.8
  permission_handler: ^10.2.0
  intl: ^0.17.0
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  google_map_polyline_new: ^0.3.0+2
  slider_button: ^2.0.0
  widget_loading: ^0.3.2

  http: 0.13.4
  shared_preferences: ^2.1.2
  toggle_switch: ^2.1.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  url_launcher: ^6.1.11
  location: ^4.4.0



  get: ^4.6.5
  

  freezed: ^2.3.2
  freezed_annotation: ^2.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
